import { repairBrands, repairServicePages } from "./app/utils/repairSeo";

const prothermWallMountedErrorCodes = [
  "f00",
  "f01",
  "f10",
  "f11",
  "f12",
  "f13",
  "f20",
  "f22",
  "f23",
  "f24",
  "f25",
  "f26",
  "f27",
  "f28",
  "f29",
  "f32",
  "f33",
  "f49",
  "f61",
  "f62",
  "f63",
  "f64",
  "f65",
  "f67",
  "f70",
  "f71",
  "f72",
  "f73",
  "f74",
  "f75",
  "f76",
  "f77",
  "f80",
  "f81",
  "f83",
  "f84",
  "f85",
  "f86",
  "f87",
  "f90",
  "f91",
];
const baxiWallMountedErrorCodes = [
  "e01",
  "e02",
  "e03",
  "e04",
  "e05",
  "e06",
  "e10",
  "e20",
  "e25",
  "e26",
  "e35",
  "e96",
  "e97",
  "e98",
  "e99",
];
const navienWallMountedErrorCodes = [
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "27",
  "30",
  "46",
  "47",
  "49",
  "56",
  "57",
  "93",
  "218",
];
const brandLandingRoutes = repairBrands.map((brand) => `/lipeck/remont/${brand.slug}/`);
const serviceLandingRoutes = repairServicePages.map((service) => `/lipeck/uslugi/${service.slug}/`);

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
    modules: ["@nuxtjs/tailwindcss"],

  devtools: { enabled: true },
  nitro: {
    prerender: {
      routes: [
        "/",
        "/lipeck/remont/",
        ...brandLandingRoutes,
        ...serviceLandingRoutes,
        ...prothermWallMountedErrorCodes.map((code) => `/lipeck/remont/protherm/oshybka-${code}/`),
        ...baxiWallMountedErrorCodes.map((code) => `/lipeck/remont/baxi/oshybka-${code}/`),
        ...navienWallMountedErrorCodes.map((code) => `/lipeck/remont/navien/oshybka-${code}/`),
      ],
    },
  },
})
